AWSTemplateFormatVersion: "2010-09-09"
Description: Multi-node cluster
Parameters:
  MasterUserPassword:
    Description: The password that is associated with the master user account for
      the cluster that is being created.
    Type: String
    Default: Qscnko123
    NoEcho: 'true'
  PortNumber:
    Description: The port number on which the cluster accepts incoming connections.
    Type: Number
    Default: '5439'
Resources:
  myCluster:
    Type: "AWS::Redshift::Cluster"
    Properties:
      DBName: "dev"
      MasterUsername: "admin"
      MasterUserPassword:
        Ref: MasterUserPassword
      NodeType: ra3.xlplus
      ClusterType: "multi-node"
      NumberOfNodes: 2
#      IamRoles:
#        - Ref: MyRedshiftS3AccessRole
      Port:
        Ref: PortNumber
      Tags:
        - Key: Owner
          Value: Sanjeev Johal
#  MyRedshiftS3AccessRole:
#    Type: AWS::IAM::Role
#    Properties:
#      RoleName: myRedshiftRole
#      AssumeRolePolicyDocument:
#        Version: "2012-10-17"
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service: redshift.amazonaws.com
#            Action: sts:AssumeRole
#      ManagedPolicyArns:
#        - arn:iac:iam::iac:policy/AmazonRedshiftReadOnlyAccess
#        - arn:iac:iam::iac:policy/AmazonS3ReadOnlyAccess
